add a separate docker-compose file for development
Gamify-IT/login-backend pull request #29
Opened 2022-07-11 18:57 UTC by robojones

Part of Gamify-IT/issues/82

2022-07-11 19:50 UTC, delvh submitted a review, later dismissed
Seems fine to me.

2022-07-11 21:39 UTC, madebyTimo requested changes

2022-07-11 21:39 UTC, madebyTimo commented on nginx/dev.conf
> +    }
sure this works?

If I see it right you proxy the api/login/ to thee host machine. Port 80 at host machine then is forwarded to the nginx and there it is proxied the frontend.

2022-07-12 20:24 UTC, LeviUniAcc approved these changes

2022-07-13 07:24 UTC, robojones commented on nginx/dev.conf
> +    }
Good point. Not sure what I was thinking there

2022-07-13 07:55 UTC, delvh approved these changes

2022-07-13 09:14 UTC, madebyTimo approved these changes
Looks fine, but why you made a force push? We should avoid force pushed, see point 5 [here](https://gamifyit-docs.readthedocs.io/en/latest/dev-manuals/repositories/repository-guide.html?#pull-requests)

2022-07-13 09:14 UTC, merged